config/routes.rb
# load class ApiConstraint
require 'api_constraint'

Rails.application.routes.draw do

  get 'friendship/create'

  get 'friendship/destroy'

  resources :albums
  post '/uploader', to: 'uploader#upload', as: :upload
  get '/uploader/finish', to: 'uploader#finish'
  post '/uploader/save', to: 'uploader#save', as: :save
  get '/uploader', to: 'uploader#index', as: :upload_index

  get '/explore', to: 'explore#index'
  post '/friend_with/:friend_id', to: 'explore#add_friendship', as: :friend_with

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :pins
  delete '/pins/:id/tags/:tag', to: 'pins#remove_tag'
  resources :comments, only: [:create]

  resources :family_bonds, only: [:index, :new, :create, :destroy]

  # for the Amistad model
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end

  match '/users/:id/finish_signup', to: 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :users, only: [:show, :update, :destroy] do
    member do
      get '/security/change_password/', to: 'users#form_change_password'
      patch :change_password
    end
  end

  # routes for Api
  # default response format for Api is JSON
  namespace :api, {defaults: {format: "json"}} do
    # make Api Version 1 as default Api
    # class ApiConstraint is inside lib/api_constraint.rb
    scope module: :v1, constraints: ApiConstraint.new(version: 1, default: true) do
      get '/users', to: 'users#show'
      get '/users/list', to: 'users#index'
      patch '/users/security/change_password', to: 'users#change_password'
      
      # handling log in, log out and sign up
      post 'users/sign_in', to: 'sessions#create'
      delete 'users/sign_out', to: 'sessions#destroy'
      
      # we must tell Devise to custom their routes
      devise_scope :user do
        # for sign up
        post '/users/sign_up', to: 'registrations#create'
        # for invitation 
        post '/users/invitation', to: 'invitations#create'

        # for passwords
        post '/users/password', to: 'passwords#create'
        put '/users/password', to: 'passwords#update'
      end

      resources :pins, except: [:edit, :new]
      resources :albums, except: [:edit, :new]
      resources :comments,only: :create
      resources :family_bonds, only: [:index,:create, :destroy]

      post '/user/oauth_verification/google', to: 'user/oauth_verifications#verify_google_token'

      if Rails.env.development?
        match '*path', via: [:options], to: lambda {|_| [200, {'Content-type' => 'text/plain'}, []]}
      end

    end
  end
  
  root 'index#index'

  get '*tags_list' => 'albums#index', as: :tag# this line should be last
end

app/views/shared/_header.html.haml
%nav.navbar.navbar-everbook
  .container
    .navbar-header
      %button.navbar-toggle{'type'=>"button", 'data-toggle'=>"collapse", 'data-target'=>"#navbar", 'aria-expanded'=>"true", 'aria-controls'=>"navbar"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand=link_to t('app'), root_path
    #navbar.navbar-collapse.collapse
      %form.navbar-form.navbar-left{role: 'search'}
        .form-group
          .input-group
            %span.input-group-addon.btn.logo
              %span.orange &nbsp;
            %input.form-control{type: 'text', placeholder: 'Search'}
            %span.input-group-addon.btn
              %span.fa.fa-search.orange
      %ul.nav.navbar-nav.navbar-left
        %li.responsive= link_to "EXPLORE", '/explore'
        %li.responsive= link_to "MY ALBUMS", '/albums'
        %li.responsive= link_to "INVITE", new_user_invitation_path, class: 'orange'

        %li.small-screen
          = link_to "UPLOAD", "/uploader"
        %li.small-screen
          = link_to "EDIT PROFILE", "#"
        %li.small-screen
          = link_to "CHANGE PASSWORD", security_change_password_user_path(current_user)
        %li.small-screen
          = link_to "MANAGE PAYMENT METHODS", "#"
        %li.small-screen
          = link_to "PURCHASE HISTORY", "#"
        %li.small-screen
          = link_to "SETTINGS", "#"
        %li.small-screen
          = link_to "Sign Out", destroy_user_session_path, method: :delete
      %ul.nav.navbar-nav.navbar-right
        %li.user-menu
          %a.dropdown-toggle{href: "#", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false"}
            %span.avatar-mini
              = image_tag current_user.try(:avatar), width: 40, height: 40 
            %span.welcome Welcome #{current_user.try(:first_name)}
            %span.caret
          %ul.dropdown-menu
            %li.responsive
              %a{href: "/explore"}  Explore
            %li.responsive
              %a{href: "/albums"}  My albums
            %li.responsive
              = link_to "Invite", new_user_invitation_path, class: 'orange'
            %li
              = link_to "Upload", "/uploader"
            %li
              = link_to "Edit Profile", "#"
            %li
              = link_to "Change Password", security_change_password_user_path(current_user)
            %li
              = link_to "Manage Payment Methods", "#"
            %li
              = link_to "Purchase History", "#"
            %li
              = link_to "Settings", "#"
            %li
              = link_to "Sign Out", destroy_user_session_path, method: :delete, id: "sign_out"